-- AUTO-GENERATED by scripts/gen-seed.mjs — do not edit by hand.
-- Region graph + initial neutral board + day-1 puzzle + settings.

truncate table public.orders, public.game_logs, public.daily_performance cascade;
delete from public.map_state;
delete from public.countries;
delete from public.daily_puzzles;
delete from public.global_settings;

insert into public.countries (id, name, continent, connections) values
  ('us', 'United States', 'north-america', ARRAY['canada', 'central-america', 'russia']::text[]),
  ('canada', 'Canada', 'north-america', ARRAY['us', 'greenland']::text[]),
  ('greenland', 'Greenland', 'north-america', ARRAY['canada', 'iceland']::text[]),
  ('central-america', 'Central America', 'north-america', ARRAY['us', 'venezuela']::text[]),
  ('venezuela', 'Venezuela', 'south-america', ARRAY['central-america', 'brazil', 'peru']::text[]),
  ('peru', 'Peru', 'south-america', ARRAY['venezuela', 'brazil', 'argentina']::text[]),
  ('brazil', 'Brazil', 'south-america', ARRAY['venezuela', 'peru', 'argentina', 'north-africa']::text[]),
  ('argentina', 'Argentina', 'south-america', ARRAY['peru', 'brazil']::text[]),
  ('iceland', 'Iceland', 'europe', ARRAY['greenland', 'great-britain', 'scandinavia']::text[]),
  ('great-britain', 'Great Britain', 'europe', ARRAY['iceland', 'ireland', 'scandinavia', 'northern-europe', 'western-europe']::text[]),
  ('ireland', 'Ireland', 'europe', ARRAY['great-britain', 'western-europe']::text[]),
  ('western-europe', 'Western Europe', 'europe', ARRAY['great-britain', 'ireland', 'northern-europe', 'southern-europe', 'north-africa']::text[]),
  ('northern-europe', 'Northern Europe', 'europe', ARRAY['great-britain', 'scandinavia', 'leningrad', 'western-europe', 'southern-europe', 'ukraine']::text[]),
  ('scandinavia', 'Scandinavia', 'europe', ARRAY['iceland', 'great-britain', 'northern-europe', 'leningrad']::text[]),
  ('leningrad', 'Leningrad', 'europe', ARRAY['scandinavia', 'northern-europe', 'ukraine', 'russia']::text[]),
  ('southern-europe', 'Southern Europe', 'europe', ARRAY['western-europe', 'northern-europe', 'ukraine', 'turkey', 'north-africa']::text[]),
  ('ukraine', 'Ukraine', 'europe', ARRAY['northern-europe', 'leningrad', 'southern-europe', 'turkey', 'russia']::text[]),
  ('north-africa', 'North Africa', 'africa', ARRAY['brazil', 'western-europe', 'southern-europe', 'egypt', 'east-africa', 'congo']::text[]),
  ('egypt', 'Egypt', 'africa', ARRAY['north-africa', 'east-africa', 'middle-east']::text[]),
  ('east-africa', 'East Africa', 'africa', ARRAY['egypt', 'north-africa', 'congo', 'south-africa', 'madagascar', 'middle-east']::text[]),
  ('congo', 'Congo', 'africa', ARRAY['north-africa', 'east-africa', 'south-africa']::text[]),
  ('south-africa', 'South Africa', 'africa', ARRAY['congo', 'east-africa', 'madagascar']::text[]),
  ('madagascar', 'Madagascar', 'africa', ARRAY['east-africa', 'south-africa']::text[]),
  ('turkey', 'Turkey', 'asia', ARRAY['southern-europe', 'ukraine', 'middle-east']::text[]),
  ('middle-east', 'Middle East', 'asia', ARRAY['turkey', 'egypt', 'east-africa', 'ural', 'afghanistan', 'india']::text[]),
  ('afghanistan', 'Afghanistan', 'asia', ARRAY['ural', 'china', 'india', 'middle-east']::text[]),
  ('ural', 'Ural', 'asia', ARRAY['russia', 'china', 'afghanistan', 'middle-east']::text[]),
  ('india', 'India', 'asia', ARRAY['afghanistan', 'china', 'middle-east', 'siam']::text[]),
  ('china', 'China', 'asia', ARRAY['russia', 'ural', 'mongolia', 'afghanistan', 'india', 'siam', 'japan']::text[]),
  ('mongolia', 'Mongolia', 'asia', ARRAY['russia', 'china']::text[]),
  ('japan', 'Japan', 'asia', ARRAY['china', 'russia']::text[]),
  ('siam', 'Siam', 'asia', ARRAY['china', 'india', 'indonesia']::text[]),
  ('russia', 'Russia', 'asia', ARRAY['leningrad', 'ukraine', 'ural', 'mongolia', 'china', 'japan', 'us']::text[]),
  ('indonesia', 'Indonesia', 'oceania', ARRAY['siam', 'new-guinea', 'australia']::text[]),
  ('new-guinea', 'New Guinea', 'oceania', ARRAY['indonesia', 'australia']::text[]),
  ('australia', 'Australia', 'oceania', ARRAY['indonesia', 'new-guinea']::text[]);

insert into public.map_state (country_id, owner_id, minds) values
  ('us', null, 7),
  ('canada', null, 8),
  ('greenland', null, 6),
  ('central-america', null, 6),
  ('venezuela', null, 6),
  ('peru', null, 5),
  ('brazil', null, 8),
  ('argentina', null, 6),
  ('iceland', null, 3),
  ('great-britain', null, 3),
  ('ireland', null, 3),
  ('western-europe', null, 5),
  ('northern-europe', null, 4),
  ('scandinavia', null, 4),
  ('leningrad', null, 4),
  ('southern-europe', null, 4),
  ('ukraine', null, 5),
  ('north-africa', null, 8),
  ('egypt', null, 5),
  ('east-africa', null, 7),
  ('congo', null, 7),
  ('south-africa', null, 7),
  ('madagascar', null, 4),
  ('turkey', null, 5),
  ('middle-east', null, 7),
  ('afghanistan', null, 4),
  ('ural', null, 6),
  ('india', null, 6),
  ('china', null, 7),
  ('mongolia', null, 5),
  ('japan', null, 3),
  ('siam', null, 5),
  ('russia', null, 8),
  ('indonesia', null, 6),
  ('new-guinea', null, 4),
  ('australia', null, 7);

insert into public.global_settings (key, value) values
  ('current_day', '1'::jsonb),
  ('resolving', 'false'::jsonb),
  ('last_resolved_day', '0'::jsonb);

insert into public.daily_puzzles
  (day_number, word_solution, word_length,
   numbers_target, numbers_pool,
   code_solution, code_length, symbol_palette) values
  (1, 'AGENT', 5,
   300, ARRAY[2,3,4,5,10,25]::int[],
   ARRAY['CIPHER','ALPHA','FLUX','BRAVO']::text[], 4,
   ARRAY['ALPHA','BRAVO','CIPHER','DELTA','ECHO','FLUX']::text[]);
