// Generates supabase/seed.sql from the canonical region graph.
// Run:  node scripts/gen-seed.mjs
import { writeFileSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { merge } from "topojson-client";
import { geoArea } from "d3-geo";
import { REGIONS } from "../lib/game/regions.data.mjs";
import { GEO_TO_GAME_ID } from "../lib/map/region-geo.data.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const out = resolve(__dirname, "../supabase/seed.sql");
const topoPath = resolve(__dirname, "../node_modules/world-atlas/countries-110m.json");

const sqlStr = (s) => `'${String(s).replace(/'/g, "''")}'`;
const sqlArr = (arr) => `ARRAY[${arr.map(sqlStr).join(", ")}]::text[]`;

// ── Neutral garrison scaled by real-world region size ───────────────────────
// Bigger regions start with a larger neutral garrison (harder to annex). We
// rank regions by true (spherical) surface area and spread garrisons evenly
// across GARRISON_MIN..GARRISON_MAX, so size ordering is always respected
// regardless of the (very skewed) absolute area distribution.
const GARRISON_MIN = 3;
const GARRISON_MAX = 8;

const topo = JSON.parse(readFileSync(topoPath, "utf8"));
const geoms = topo.objects.countries.geometries;
const byRegion = {};
for (const g of geoms) {
  const rid = GEO_TO_GAME_ID[String(g.id)];
  if (rid) (byRegion[rid] ??= []).push(g);
}
const areaByRegion = Object.fromEntries(
  Object.entries(byRegion).map(([rid, gs]) => [rid, geoArea(merge(topo, gs))]),
);
// rank ascending by area → 0 (smallest) .. n-1 (largest)
const rankByRegion = {};
Object.keys(areaByRegion)
  .sort((a, b) => areaByRegion[a] - areaByRegion[b])
  .forEach((rid, i) => (rankByRegion[rid] = i));

const n = REGIONS.length;
const garrison = (region) => {
  const rank = rankByRegion[region.id] ?? 0;
  const span = GARRISON_MAX - GARRISON_MIN;
  return GARRISON_MIN + Math.round((span * rank) / (n - 1));
};

const lines = [];
lines.push("-- AUTO-GENERATED by scripts/gen-seed.mjs — do not edit by hand.");
lines.push("-- Region graph + initial neutral board + day-1 puzzle + settings.\n");

lines.push("truncate table public.orders, public.game_logs, public.daily_performance cascade;");
lines.push("delete from public.map_state;");
lines.push("delete from public.countries;");
lines.push("delete from public.daily_puzzles;");
lines.push("delete from public.global_settings;\n");

// countries
lines.push("insert into public.countries (id, name, continent, connections) values");
lines.push(
  REGIONS.map(
    (r) => `  (${sqlStr(r.id)}, ${sqlStr(r.name)}, ${sqlStr(r.continent)}, ${sqlArr(r.connections)})`,
  ).join(",\n") + ";\n",
);

// initial neutral board
lines.push("insert into public.map_state (country_id, owner_id, minds) values");
lines.push(
  REGIONS.map((r) => `  (${sqlStr(r.id)}, null, ${garrison(r)})`).join(",\n") + ";\n",
);

// global settings
lines.push("insert into public.global_settings (key, value) values");
lines.push(
  [
    `  ('current_day', '1'::jsonb)`,
    `  ('resolving', 'false'::jsonb)`,
    `  ('last_resolved_day', '0'::jsonb)`,
  ].join(",\n") + ";\n",
);

// day-1 puzzle (hand-authored, known-good). Future days are generated by the
// resolution engine (lib/game/puzzles.ts).
lines.push(`insert into public.daily_puzzles
  (day_number, word_solution, word_length,
   numbers_target, numbers_pool,
   code_solution, code_length, symbol_palette) values
  (1, 'AGENT', 5,
   300, ARRAY[2,3,4,5,10,25]::int[],
   ARRAY['CIPHER','ALPHA','FLUX','BRAVO']::text[], 4,
   ARRAY['ALPHA','BRAVO','CIPHER','DELTA','ECHO','FLUX']::text[]);\n`);

writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${out} (${REGIONS.length} regions).`);
